apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand
  template:
    metadata:
      labels:
        app: rand
    spec:
      containers:
      - image: okteto.dev/rand:latest
        name: rand
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "eb45a160-1a7b-4704-a8a5-3331687b19f7"
        - name: Vless_Path
          value: "/vlefsh"
        - name: Vmess_UUID
          value: "eb45a160-1a7b-4704-a8a5-3331687b19f7"
        - name: Vmess_Path
          value: "/vmfddf"
        - name: Share_Path
          value: "/v2link"
